In [7]:
import pandas as pd

# Load the file
# 'sep' might need to be '\s+' if it uses multiple spaces instead of tabs
df = pd.read_csv('metal_eGFR_meta1.TBL.map.annot.gc.gz', sep='\s+', compression='gzip')

<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
/var/folders/z7/9ddbbmc16r938ffjjlj2ssv40000gn/T/ipykernel_94133/713784.py:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df = pd.read_csv('metal_eGFR_meta1.TBL.map.annot.gc.gz', sep='\s+', compression='gzip')

In [8]:
df.head()

,MarkerName,Allele1,Allele2,n,Freq1,Effect,StdErr,P.value,Direction,mac,chr,pos,P.value.GC,StdErr.GC,RSID
0,10:10000018:A_G,a,g,1062160.0,0.5719,-0.0008,0.0003,0.004116,--,9.094214e+05,10,10000018,0.01136,0.000340,rs6602381
1,10:100000625:A_G,a,g,1201910.0,0.5631,-0.0007,0.0003,0.004173,--,1.050229e+06,10,100000625,0.01148,0.000340,rs7899632
2,10:100000645:A_C,a,c,1201910.0,0.7974,-0.0008,0.0003,0.019440,--,4.870139e+05,10,100000645,0.03921,0.000340,rs61875309
3,10:100003242:G_T,t,g,1201920.0,0.8633,0.0002,0.0004,0.634100,-+,3.286049e+05,10,100003242,0.67450,0.000453,rs12258651
4,10:100003304:A_G,a,g,940166.0,0.9601,0.0007,0.0007,0.326400,++,7.502525e+04,10,100003304,0.38650,0.000793,rs72828461

In [12]:
df

,MarkerName,Allele1,Allele2,n,Freq1,Effect,StdErr,P.value,Direction,mac,chr,pos,P.value.GC,StdErr.GC,RSID
0,10:10000018:A_G,a,g,1062160.0,0.5719,-0.0008,0.0003,0.004116,--,9.094214e+05,10,10000018,0.01136,0.000340,rs6602381
1,10:100000625:A_G,a,g,1201910.0,0.5631,-0.0007,0.0003,0.004173,--,1.050229e+06,10,100000625,0.01148,0.000340,rs7899632
2,10:100000645:A_C,a,c,1201910.0,0.7974,-0.0008,0.0003,0.019440,--,4.870139e+05,10,100000645,0.03921,0.000340,rs61875309
3,10:100003242:G_T,t,g,1201920.0,0.8633,0.0002,0.0004,0.634100,-+,3.286049e+05,10,100003242,0.67450,0.000453,rs12258651
4,10:100003304:A_G,a,g,940166.0,0.9601,0.0007,0.0007,0.326400,++,7.502525e+04,10,100003304,0.38650,0.000793,rs72828461
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8258048,9:99997596:A_G,a,g,1016310.0,0.0544,0.0007,0.0013,0.600200,-+,1.105745e+05,9,99997596,0.64380,0.001473,rs41405653
8258049,9:99997707:C_T,t,c,1136440.0,0.4516,-0.0001,0.0003,0.685400,+-,1.026433e+06,9,99997707,0.72080,0.000340,rs11794422
8258050,9:99998403:C_T,t,c,1178670.0,0.4394,-0.0002,0.0003,0.493900,+-,1.035815e+06,9,99998403,0.54610,0.000340,rs10981296
8258051,9:99998646:C_G,c,g,1177510.0,0.7840,0.0000,0.0003,0.885900,+-,5.086843e+05,9,99998646,0.89930,0.000340,rs10981297
8258052,9:99999468:A_G,a,g,1178630.0,0.8914,-0.0009,0.0004,0.039280,--,2.559984e+05,9,99999468,0.06896,0.000453,rs10981301

In [14]:
df[df['P.value.GC'] < 5e-08].to_csv('significant_results.csv', index=False)